jobs:
  test:
    executor:
      name: go/default
      tag: "1.18"
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - run:
          name: goimports
          command: |
            go install golang.org/x/tools/cmd/goimports
      - go/save-cache
      - go/test:
          covermode: atomic
          failfast: true
          race: true

  lint:
    executor:
      name: go/default
      tag: "1.14"
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - run:
          name: downloads
          command: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
            go install github.com/matthewloring/validjson/cmd/validjson
      - go/save-cache
      - run:
          name: lint
          command: |
            golangci-lint run ./...
            validjson ./...

version: 2.1
orbs:
  go: circleci/go@1.7.1
workflows:
  main:
    jobs:
      - test
      - lint
