jobs:
  test:
    docker:
      - image: cimg/go:1.18.1
    steps:
      - checkout
      - run:
          name: goimports
          command: |
            go install golang.org/x/tools/cmd/goimports
      - run:
          name: test
          command: |
            go test -race -count=1 -covermode=atomic ./...

  lint:
    docker:
      - image: cimg/go:1.18.1
    steps:
      - checkout
      - run:
          name: downloads
          command: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/
      - run:
          name: lint
          command: |
            golangci-lint run ./...

version: 2.1
workflows:
  main:
    jobs:
      - test
      - lint
