version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run: go install golang.org/x/tools/cmd/goimports
      - run:
          name: build
          command: |
            set -eux -o pipefail 
            go build ./cmd/goannotate/annotators/testdata/impl
            go build cloudeng.io/go/cmd/goannotate/annotators/testdata/impl
            go get -v -t -d ./...
            go test -v ./...
