annotations:
  # annotators contains an entry for each supported annotation. The
  # configuration for each annotation depends on the annotator itself except
  # that all annotators must have a 'type' key that names the go type of tha
  # annotator and a 'name' key than names the annotation. Each annotator must
  # be compiled in to the goannotate binary priort to it being usable here.
  # The --list command will provide documentation on the current set of compiled
  # in annotators.
  - type: cloudeng.io/go/cmd/goannotate/annotators.AddLogCall
    name: vanadium-add-logcall
    # Packages specifies the packaages to be annotated. It may be overriden
    # from the command line.
    packages:
      - "v.io/x/ref/runtime/internal/naming/namespace"
    interfaces:
      - "v.io/v23/namespace"
    functions:
    contextType: v.io/v23/context.T
    import: v.io/x/ref/lib/apilog    logcall: apilog.LogCallf2
    ignoreEmptyFunctions: true
  - type: cloudeng.io/go/cmd/goannotate/annotators.RmLogCall
    name: vanadium-rm-logcall
    packages:
      - "v.io/x/ref/..."
    interfaces:
      - "v.io/v23/namespace"
    functions:
    logcall: apilog.LogCallf
    comment: "gologcop: DO NOT EDIT, MUST BE FIRST STATEMENT"
    deferred: true
  - type: cloudeng.io/go/cmd/goannotate/annotators.EnsureCopyrightAndLicense
    name: personal-copyright
    copyright: "// Copyright 2020 Cosmos Nicolaou. All rights reserved."
    license: "// Use of this source code is governed by the Apache-2.0\n
// license that can be found in the LICENSE file."
  - type: cloudeng.io/go/cmd/goannotate/annotators.EnsureCopyrightAndLicense
    name: cloudeng-copyright
    copyright: "// Copyright 2020 cloudeng llc. All rights reserved."
    license: "// Use of this source code is governed by the Apache-2.0\n
// license that can be found in the LICENSE file."
options:
  concurrency: 0
debug:
  cpu_profile:
