name: windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.23.x]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          go install cloudeng.io/citools/multimod@latest
          go install golang.org/x/tools/cmd/goimports@latest

      - name: Test
        run: multimod --config=.multimod.yaml test
